name: Upload to Barbarian

# Run the workflow manually from the web UI with parameters to control
# what it runs.
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The github ref hosting the package"
        required: true
      recipe_path:
        description: "The path to the recipe to upload"
        required: true
      package_name:
        description: "The name of the package to upload"
        required: true
      package_version:
        description: "The version number of the package to upload"
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Install Test Barbarian
        run: |
          pip install conan sty
          pip install -i https://test.pypi.org/simple/ barbarian
      - uses: ericLemanissier/barbarian-upload@v1.0.0
        with:
          recipe_path: ${{ github.event.inputs.recipe_path }}
          package_name: ${{ github.event.inputs.package_name }}
          package_version: ${{ github.event.inputs.package_version }}
